# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  name: pilot

registry:
  containerPort: 8080

  image:
    url: docker.io
    name: chartmuseum/chartmuseum
    version: latest

  app:
    env:
      debugEnabled: true
      storageName: local
      storageRootDir: /charts

rbac:
  serviceAccount:
    name: pilot-account
  crb:
    name: pilot-cbr
  role:
    name: pilot-role

nodeSelector: {}

tolerations: []

affinity: {}
